


spring:
  application:
    name: demo
  cloud:
    nacos:
      discovery:
        server-addr: http://120.27.215.119:8848/
logging:
  level:
    root: info
    org.springframework: info


server:
  port: 8081